### ISSUE TITLE
Criar modal De cadastro

### ISSUE THREAD

**Issue by Filipe-barbosa** [Filipe-barbosa/smartCalendarAPP#9]
### Motivação 

Buscando evoluir com o produto, faz-se necessária a criação de uma modal de cadastro, para a inserção de novos usuários. 

### O que fazer 

Criar um botão na  rota principal com o nome de "Novo Cadastro", que ao ser clicado sera capaz abrir uma modal que englobará toda a tela e  renderize  um componente de formulário. 

### Critérios de aceite
- o texto do botão  deverá estar em um arquivo de tradução. 
- a modal terá de renderizar o componente no centro da tela. 
- o botão de fechar e de responsabilidade desta task

**Comment by Joel-leal** [comment]
Sugestão de alguma biblioteca?
